version: '3.8'

services:
  backend:
    build: .
    container_name: ecommerce-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - ecommerce-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
