version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - '3000:5000' # Porta do contêiner mapeada para 5000 (do .env)
    env_file: 
      - .env  # Carrega as variáveis do arquivo .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    command: npm run dev

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo-data: